# Generated by Django 3.0.5 on 2020-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstLevelDecryption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=4)),
                ('value', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FirstLevelEncryption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1)),
                ('value', models.CharField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='FirstLevelEncryptionDecryption',
        ),
    ]
