# Generated by Django 3.0.5 on 2020-04-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200427_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultaccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='defaultaccount',
            name='password',
        ),
    ]
