# Generated by Django 3.0.5 on 2020-04-20 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20200416_2105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultAccount',
            new_name='DefaultAccounts',
        ),
    ]
