# Generated by Django 3.0.5 on 2020-04-20 17:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_auto_20200420_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultAccounts',
            new_name='DefaultAccount',
        ),
    ]
