# Generated by Django 3.0.5 on 2020-04-23 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200420_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldsForDefaultAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
                ('field_value', models.CharField(max_length=100)),
                ('default_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DefaultAccount')),
            ],
        ),
    ]
