# Generated by Django 3.0.5 on 2020-04-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='profile',
            field=models.ImageField(default='default_user.png', upload_to='profile_pics'),
        ),
    ]
